name: Build-Test-Release

on:
  push:
    branches:
      - nx_release_2

jobs:
  build-test-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npx nx build @nabalones/language-chooser-react-mui

      - name: Run tests
        run: npx nx test @nabalones/find-language

      - name: Clean up package.json
        run: npm pkg delete devDependencies && npm pkg delete dependencies

      # Done manually because of semantic-release, copied from bloom-player
      - name: Clean up package.json
        run: npm pkg delete scripts && npm pkg delete devDependencies && npm pkg delete dependencies

      - name: Print Environment Info
        run: npx nx report

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx nx release
