name: Build-Test-Release

on:
  push:
    branches:
      - gha_test

jobs:
  build-test-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build --prefix components/language-picker/common/find-language/

      - name: Run tests
        run: npm run test --prefix components/language-picker/common/find-language/
